### ISSUE TITLE
FR: Would it be possible for binaries to be made available in the repo?

### ISSUE THREAD

**Issue by ccatlett1984** [deepnest-next/deepnest#4]
I see that a CI build test is already being ran, could we get the build artifacts made available (for those that can't / don't know how to build from source)?

**Comment by Dexus** [comment]
Hi @ccatlett1984 sure, it will take some time because I need to write a proper Job/Workflow to build the Binaries and set up the SignCerts first. So we will be able starting 2025 automatically release the files.

But for you, I will run later the Build and create a release file.

**Comment by Dexus** [comment]
@ccatlett1984 I have now created the first [release](https://github.com/deepnest-next/deepnest/releases/tag/v1.2.2).
